[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = [
    "-v",
    "--tb=short", 
    "--maxfail=5"
]
minversion = "6.0"
markers = [
    "slow: marks tests as slow (real TTS engines, file I/O heavy)",
    "integration: marks tests as integration tests (cross-component)", 
    "real_engine: marks tests that require real TTS engines",
    "e2e: marks tests as end-to-end tests",
    "unit: marks tests as unit tests (fast, isolated)",
    "asyncio: marks tests as asyncio-based tests"
]

# Parallel execution configuration
# Note: looponfailroots is deprecated in pytest-xdist 4.0, removed for clean runs
