name: CI

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Python dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          python -m pytest tests/ -v
